"""
形态/结构类规则
"""

from ..base import ConditionType, SignalRule

CANDLESTICK_RULES = [
    SignalRule(
        name="头肩顶形态",
        table="K线形态扫描器.py",
        category="pattern",
        subcategory="candlestick",
        direction="SELL",
        strength=85,
        priority="high",
        cooldown=43200,  # 12小时冷却（原2小时）
        condition_type=ConditionType.CONTAINS,
        condition_config={"field": "形态类型", "patterns": ["头肩顶"], "match_any": True},
        message_template="⚠️ 头肩顶形态 强度:{strength}",
        fields={"strength": "强度"},
    ),
    SignalRule(
        name="头肩底形态",
        table="K线形态扫描器.py",
        category="pattern",
        subcategory="candlestick",
        direction="BUY",
        strength=85,
        priority="high",
        cooldown=43200,  # 12小时冷却（原2小时）
        condition_type=ConditionType.CONTAINS,
        condition_config={"field": "形态类型", "patterns": ["头肩底"], "match_any": True},
        message_template="⚠️ 头肩底形态 强度:{strength}",
        fields={"strength": "强度"},
    ),
    SignalRule(
        name="双顶形态",
        table="K线形态扫描器.py",
        category="pattern",
        subcategory="candlestick",
        direction="SELL",
        strength=80,
        priority="high",
        cooldown=43200,  # 12小时冷却（原2小时）
        condition_type=ConditionType.CONTAINS,
        condition_config={"field": "形态类型", "patterns": ["双顶", "M顶"], "match_any": True},
        message_template="⚠️ 双顶形态 强度:{strength}",
        fields={"strength": "强度"},
    ),
    SignalRule(
        name="双底形态",
        table="K线形态扫描器.py",
        category="pattern",
        subcategory="candlestick",
        direction="BUY",
        strength=80,
        priority="high",
        cooldown=43200,  # 12小时冷却（原2小时）
        condition_type=ConditionType.CONTAINS,
        condition_config={"field": "形态类型", "patterns": ["双底", "W底"], "match_any": True},
        message_template="⚠️ 双底形态 强度:{strength}",
        fields={"strength": "强度"},
    ),
    SignalRule(
        name="三角形突破",
        table="K线形态扫描器.py",
        category="pattern",
        subcategory="candlestick",
        direction="ALERT",
        strength=70,
        priority="medium",  # 降低优先级
        cooldown=86400,  # 24小时冷却（原2小时太短）
        condition_type=ConditionType.CONTAINS,
        condition_config={"field": "形态类型", "patterns": ["三角", "楔形"], "match_any": True},
        message_template="三角/楔形形态 强度:{strength}",
        fields={"strength": "强度"},
    ),
    SignalRule(
        name="锤子线",
        table="K线形态扫描器.py",
        category="pattern",
        subcategory="candlestick",
        direction="BUY",
        strength=65,
        priority="medium",
        condition_type=ConditionType.CONTAINS,
        condition_config={"field": "形态类型", "patterns": ["锤子", "hammer"], "match_any": True},
        message_template="锤子线形态 强度:{strength}",
        fields={"strength": "强度"},
    ),
    SignalRule(
        name="吞没形态",
        table="K线形态扫描器.py",
        category="pattern",
        subcategory="candlestick",
        direction="ALERT",
        strength=70,
        priority="medium",
        condition_type=ConditionType.CONTAINS,
        condition_config={"field": "形态类型", "patterns": ["吞没", "engulf"], "match_any": True},
        message_template="吞没形态 强度:{strength}",
        fields={"strength": "强度"},
    ),
    SignalRule(
        name="十字星",
        table="K线形态扫描器.py",
        category="pattern",
        subcategory="candlestick",
        direction="ALERT",
        strength=60,
        priority="low",
        cooldown=21600,  # 6小时冷却（原无限制）
        condition_type=ConditionType.CONTAINS,
        condition_config={"field": "形态类型", "patterns": ["十字", "doji"], "match_any": True},
        message_template="十字星形态 强度:{strength}",
        fields={"strength": "强度"},
    ),
]

SMC_RULES = [
    SignalRule(
        name="SMC看涨",
        table="大资金操盘扫描器.py",
        category="pattern",
        subcategory="smc",
        direction="BUY",
        strength=75,
        priority="high",
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={"field": "偏向", "from_values": ["看跌", "中性", ""], "to_values": ["看涨"]},
        message_template="SMC看涨 评分:{score} 结构:{event}",
        fields={"score": "评分", "event": "结构事件"},
    ),
    SignalRule(
        name="SMC看跌",
        table="大资金操盘扫描器.py",
        category="pattern",
        subcategory="smc",
        direction="SELL",
        strength=75,
        priority="high",
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={"field": "偏向", "from_values": ["看涨", "中性", ""], "to_values": ["看跌"]},
        message_template="SMC看跌 评分:{score} 结构:{event}",
        fields={"score": "评分", "event": "结构事件"},
    ),
    SignalRule(
        name="BOS突破",
        table="大资金操盘扫描器.py",
        category="pattern",
        subcategory="smc",
        direction="ALERT",
        strength=70,
        priority="high",
        condition_type=ConditionType.CONTAINS,
        condition_config={"field": "结构事件", "patterns": ["BOS"], "match_any": True},
        message_template="BOS结构突破 方向:{dir}",
        fields={"dir": "方向"},
    ),
    SignalRule(
        name="CHoCH变化",
        table="大资金操盘扫描器.py",
        category="pattern",
        subcategory="smc",
        direction="ALERT",
        strength=75,
        priority="high",
        condition_type=ConditionType.CONTAINS,
        condition_config={"field": "结构事件", "patterns": ["CHoCH", "CHOCH"], "match_any": True},
        message_template="CHoCH结构变化 方向:{dir}",
        fields={"dir": "方向"},
    ),
]

FIBONACCI_RULES = [
    SignalRule(
        name="斐波那契多头信号",
        table="量能斐波狙击扫描器.py",
        category="pattern",
        subcategory="fibonacci",
        direction="BUY",
        strength=70,
        priority="high",
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={"field": "方向", "from_values": ["空", "down", "-1", ""], "to_values": ["多", "up", "1"]},
        message_template="斐波那契多头 区域:{zone} 强度:{strength}",
        fields={"zone": "价格区域", "strength": "强度"},
    ),
    SignalRule(
        name="斐波那契空头信号",
        table="量能斐波狙击扫描器.py",
        category="pattern",
        subcategory="fibonacci",
        direction="SELL",
        strength=70,
        priority="high",
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={"field": "方向", "from_values": ["多", "up", "1", ""], "to_values": ["空", "down", "-1"]},
        message_template="斐波那契空头 区域:{zone} 强度:{strength}",
        fields={"zone": "价格区域", "strength": "强度"},
    ),
]

VPVR_RULES = [
    SignalRule(
        name="进入VPVR价值区",
        table="VPVR排行生成器.py",
        category="pattern",
        subcategory="vpvr",
        direction="ALERT",
        strength=55,
        priority="low",
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={"field": "价值区位置", "from_values": ["上方", "下方"], "to_values": ["价值区内"]},
        message_template="进入VPVR价值区 POC:{poc}",
        fields={"poc": "控制点价格"},
    ),
    SignalRule(
        name="离开VPVR价值区",
        table="VPVR排行生成器.py",
        category="pattern",
        subcategory="vpvr",
        direction="ALERT",
        strength=60,
        priority="medium",
        condition_type=ConditionType.STATE_CHANGE,
        condition_config={"field": "价值区位置", "from_values": ["价值区内"], "to_values": ["上方", "下方"]},
        message_template="离开VPVR价值区 位置:{pos}",
        fields={"pos": "价值区位置"},
    ),
]

PATTERN_RULES = CANDLESTICK_RULES + SMC_RULES + FIBONACCI_RULES + VPVR_RULES
